runtime: aspnetcore
env: flex

resources:
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 800
  cpu_utilization:
    target_utilization: 0.9
liveness_check:
  check_interval_sec: 80
  timeout_sec: 15
  failure_threshold: 5
readiness_check:
  check_interval_sec: 30
  timeout_sec: 15
  failure_threshold: 5